// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-typesonly

export interface ServiceError {
  code: number;
  message: string;
}

export type PlayerID = string;

export type RoomID = string;

export type Timestamp = string;

export interface Position {
  tileX: number;
  tileY: number;
  subX: number;
  subY: number;
  layer: number;
}

export interface Player {
  playerId: PlayerID;
  name: string;
  roomId: RoomID;
  pos: Position;
}

export interface ChatMessage {
  playerId: PlayerID;
  name: string;
  message: string;
  at: Timestamp;
}

export interface RoomState {
  roomId: RoomID;
  players: Player[];
  recentChat: ChatMessage[];
  fieldW: number;
  fieldH: number;
}

export interface JoinRequest {
  name: string;
  roomId?: RoomID;
}

export interface JoinResponse {
  player: Player;
  room: RoomState;
}

export interface MoveRequest {
  dx: number;
  dy: number;
}

export interface SayRequest {
  message: string;
}

export interface FireworkIntent {
}

export interface CheckNameRequest {
  name: string;
}

export interface NameAvailability {
  name: string;
  available: boolean;
}

export interface Tick {
  players: Player[];
}

export interface FireworkEvent {
  playerId: PlayerID;
}

export interface ErrorEvent {
  code: number;
  message: string;
}

