// Package api contains generated service interfaces.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

import (
	"context"
)

// WorldService defines the service interface
type WorldService interface {
	Join(ctx context.Context, req JoinRequest) (JoinResponse, error)
	MovePlayer(ctx context.Context, req MoveRequest) (Player, error)
	GetRoomState(ctx context.Context, req GetRoomStateRequest) (RoomState, error)
	Say(ctx context.Context, req SayRequest) (RoomState, error)
}
