// Package api contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

// PlayerID is a type alias
type PlayerID string

// RoomID is a type alias
type RoomID string

// Timestamp is a type alias
type Timestamp string

// Position represents a structured data type
type Position struct {
	TileX int64  `json:"tile_x" yaml:"tile_x" cbor:"tile_x"`
	TileY int64  `json:"tile_y" yaml:"tile_y" cbor:"tile_y"`
	SubX  uint64 `json:"sub_x" yaml:"sub_x" cbor:"sub_x"`
	SubY  uint64 `json:"sub_y" yaml:"sub_y" cbor:"sub_y"`
	Layer int64  `json:"layer" yaml:"layer" cbor:"layer"`
}

// Player represents a structured data type
type Player struct {
	PlayerId PlayerID `json:"player_id" yaml:"player_id" cbor:"player_id"`
	Name     string   `json:"name" yaml:"name" cbor:"name"`
	RoomId   RoomID   `json:"room_id" yaml:"room_id" cbor:"room_id"`
	Pos      Position `json:"pos" yaml:"pos" cbor:"pos"`
}

// ChatMessage represents a structured data type
type ChatMessage struct {
	PlayerId PlayerID  `json:"player_id" yaml:"player_id" cbor:"player_id"`
	Name     string    `json:"name" yaml:"name" cbor:"name"`
	Message  string    `json:"message" yaml:"message" cbor:"message"`
	At       Timestamp `json:"at" yaml:"at" cbor:"at"`
}

// RoomState represents a structured data type
type RoomState struct {
	RoomId     RoomID        `json:"room_id" yaml:"room_id" cbor:"room_id"`
	Players    []Player      `json:"players" yaml:"players" cbor:"players"`
	RecentChat []ChatMessage `json:"recent_chat" yaml:"recent_chat" cbor:"recent_chat"`
	FieldW     uint64        `json:"field_w" yaml:"field_w" cbor:"field_w"`
	FieldH     uint64        `json:"field_h" yaml:"field_h" cbor:"field_h"`
}

// JoinRequest represents a structured data type
type JoinRequest struct {
	Name   string  `json:"name" yaml:"name" cbor:"name"`
	RoomId *RoomID `json:"room_id,omitempty" yaml:"room_id,omitempty" cbor:"room_id,omitempty"`
}

// JoinResponse represents a structured data type
type JoinResponse struct {
	Player Player    `json:"player" yaml:"player" cbor:"player"`
	Room   RoomState `json:"room" yaml:"room" cbor:"room"`
}

// MoveRequest represents a structured data type
type MoveRequest struct {
	Dx int64 `json:"dx" yaml:"dx" cbor:"dx"`
	Dy int64 `json:"dy" yaml:"dy" cbor:"dy"`
}

// GetRoomStateRequest represents a structured data type
type GetRoomStateRequest struct {
	RoomId *RoomID `json:"room_id,omitempty" yaml:"room_id,omitempty" cbor:"room_id,omitempty"`
}

// SayRequest represents a structured data type
type SayRequest struct {
	Message string `json:"message" yaml:"message" cbor:"message"`
}

// CheckNameRequest represents a structured data type
type CheckNameRequest struct {
	Name string `json:"name" yaml:"name" cbor:"name"`
}

// NameAvailability represents a structured data type
type NameAvailability struct {
	Name      string `json:"name" yaml:"name" cbor:"name"`
	Available bool   `json:"available" yaml:"available" cbor:"available"`
}

// Tick represents a structured data type
type Tick struct {
	Players []Player `json:"players" yaml:"players" cbor:"players"`
}

// FireworkEvent represents a structured data type
type FireworkEvent struct {
	PlayerId PlayerID `json:"player_id" yaml:"player_id" cbor:"player_id"`
}

// ErrorEvent represents a structured data type
type ErrorEvent struct {
	Code    int64  `json:"code" yaml:"code" cbor:"code"`
	Message string `json:"message" yaml:"message" cbor:"message"`
}

// ClientMessage represents a structured data type
type ClientMessage struct {
	Kind string `json:"kind" yaml:"kind" cbor:"kind"`
	Body []byte `json:"body" yaml:"body" cbor:"body"`
}

// ServerMessage represents a structured data type
type ServerMessage struct {
	Event string `json:"event" yaml:"event" cbor:"event"`
	Body  []byte `json:"body" yaml:"body" cbor:"body"`
}
